In [2]:
import pandas as pd

final = pd.read_csv("../../data/processed/final_dataset_clean.csv")
print(final.columns.tolist())

['site_RBD', 'site_SARS2', 'wildtype', 'mutant', 'mutation', 'mutation_RBD', 'bind_lib1', 'bind_lib2', 'ace2_score', 'expr_lib1', 'expr_lib2', 'expr_score', 'mut_id', 'label', 'pos', 'wt', 'mut', 'blosum62', 'grantham', 'delta_charge', 'delta_hydro', 'delta_volume', 'delta_polarity', 'is_stop', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31', '32', '33', '34', '35', '36', '37', '38', '39', '40', '41', '42', '43', '44', '45', '46', '47', '48', '49', '50', '51', '52', '53', '54', '55', '56', '57', '58', '59', '60', '61', '62', '63', '64', '65', '66', '67', '68', '69', '70', '71', '72', '73', '74', '75', '76', '77', '78', '79', '80', '81', '82', '83', '84', '85', '86', '87', '88', '89', '90', '91', '92', '93', '94', '95', '96', '97', '98', '99', '100', '101', '102', '103', '104', '105', '106', '107', '108', '109', '110', '111', '112', '113', '114', '115', '116', '117', '118', '119', '120', '121', '122', '123', '124', '125', '126', '127', '128', '129', '130', '131', '132', '133', '134', '135', '136', '137', '138', '139', '140', '141', '142', '143', '144', '145', '146', '147', '148', '149', '150', '151', '152', '153', '154', '155', '156', '157', '158', '159', '160', '161', '162', '163', '164', '165', '166', '167', '168', '169', '170', '171', '172', '173', '174', '175', '176', '177', '178', '179', '180', '181', '182', '183', '184', '185', '186', '187', '188', '189', '190', '191', '192', '193', '194', '195', '196', '197', '198', '199', '200', '201', '202', '203', '204', '205', '206', '207', '208', '209', '210', '211', '212', '213', '214', '215', '216', '217', '218', '219', '220', '221', '222', '223', '224', '225', '226', '227', '228', '229', '230', '231', '232', '233', '234', '235', '236', '237', '238', '239', '240', '241', '242', '243', '244', '245', '246', '247', '248', '249', '250', '251', '252', '253', '254', '255', '256', '257', '258', '259', '260', '261', '262', '263', '264', '265', '266', '267', '268', '269', '270', '271', '272', '273', '274', '275', '276', '277', '278', '279', '280', '281', '282', '283', '284', '285', '286', '287', '288', '289', '290', '291', '292', '293', '294', '295', '296', '297', '298', '299', '300', '301', '302', '303', '304', '305', '306', '307', '308', '309', '310', '311', '312', '313', '314', '315', '316', '317', '318', '319', '320', '321', '322', '323', '324', '325', '326', '327', '328', '329', '330', '331', '332', '333', '334', '335', '336', '337', '338', '339', '340', '341', '342', '343', '344', '345', '346', '347', '348', '349', '350', '351', '352', '353', '354', '355', '356', '357', '358', '359', '360', '361', '362', '363', '364', '365', '366', '367', '368', '369', '370', '371', '372', '373', '374', '375', '376', '377', '378', '379', '380', '381', '382', '383', '384', '385', '386', '387', '388', '389', '390', '391', '392', '393', '394', '395', '396', '397', '398', '399', '400', '401', '402', '403', '404', '405', '406', '407', '408', '409', '410', '411', '412', '413', '414', '415', '416', '417', '418', '419', '420', '421', '422', '423', '424', '425', '426', '427', '428', '429', '430', '431', '432', '433', '434', '435', '436', '437', '438', '439', '440', '441', '442', '443', '444', '445', '446', '447', '448', '449', '450', '451', '452', '453', '454', '455', '456', '457', '458', '459', '460', '461', '462', '463', '464', '465', '466', '467', '468', '469', '470', '471', '472', '473', '474', '475', '476', '477', '478', '479', '480', '481', '482', '483', '484', '485', '486', '487', '488', '489', '490', '491', '492', '493', '494', '495', '496', '497', '498', '499', '500', '501', '502', '503', '504', '505', '506', '507', '508', '509', '510', '511', '512', '513', '514', '515', '516', '517', '518', '519', '520', '521', '522', '523', '524', '525', '526', '527', '528', '529', '530', '531', '532', '533', '534', '535', '536', '537', '538', '539', '540', '541', '542', '543', '544', '545', '546', '547', '548', '549', '550', '551', '552', '553', '554', '555', '556', '557', '558', '559', '560', '561', '562', '563', '564', '565', '566', '567', '568', '569', '570', '571', '572', '573', '574', '575', '576', '577', '578', '579', '580', '581', '582', '583', '584', '585', '586', '587', '588', '589', '590', '591', '592', '593', '594', '595', '596', '597', '598', '599', '600', '601', '602', '603', '604', '605', '606', '607', '608', '609', '610', '611', '612', '613', '614', '615', '616', '617', '618', '619', '620', '621', '622', '623', '624', '625', '626', '627', '628', '629', '630', '631', '632', '633', '634', '635', '636', '637', '638', '639', '640', '641', '642', '643', '644', '645', '646', '647', '648', '649', '650', '651', '652', '653', '654', '655', '656', '657', '658', '659', '660', '661', '662', '663', '664', '665', '666', '667', '668', '669', '670', '671', '672', '673', '674', '675', '676', '677', '678', '679', '680', '681', '682', '683', '684', '685', '686', '687', '688', '689', '690', '691', '692', '693', '694', '695', '696', '697', '698', '699', '700', '701', '702', '703', '704', '705', '706', '707', '708', '709', '710', '711', '712', '713', '714', '715', '716', '717', '718', '719', '720', '721', '722', '723', '724', '725', '726', '727', '728', '729', '730', '731', '732', '733', '734', '735', '736', '737', '738', '739', '740', '741', '742', '743', '744', '745', '746', '747', '748', '749', '750', '751', '752', '753', '754', '755', '756', '757', '758', '759', '760', '761', '762', '763', '764', '765', '766', '767', '768', '769', '770', '771', '772', '773', '774', '775', '776', '777', '778', '779', '780', '781', '782', '783', '784', '785', '786', '787', '788', '789', '790', '791', '792', '793', '794', '795', '796', '797', '798', '799', '800', '801', '802', '803', '804', '805', '806', '807', '808', '809', '810', '811', '812', '813', '814', '815', '816', '817', '818', '819', '820', '821', '822', '823', '824', '825', '826', '827', '828', '829', '830', '831', '832', '833', '834', '835', '836', '837', '838', '839', '840', '841', '842', '843', '844', '845', '846', '847', '848', '849', '850', '851', '852', '853', '854', '855', '856', '857', '858', '859', '860', '861', '862', '863', '864', '865', '866', '867', '868', '869', '870', '871', '872', '873', '874', '875', '876', '877', '878', '879', '880', '881', '882', '883', '884', '885', '886', '887', '888', '889', '890', '891', '892', '893', '894', '895', '896', '897', '898', '899', '900', '901', '902', '903', '904', '905', '906', '907', '908', '909', '910', '911', '912', '913', '914', '915', '916', '917', '918', '919', '920', '921', '922', '923', '924', '925', '926', '927', '928', '929', '930', '931', '932', '933', '934', '935', '936', '937', '938', '939', '940', '941', '942', '943', '944', '945', '946', '947', '948', '949', '950', '951', '952', '953', '954', '955', '956', '957', '958', '959', '960', '961', '962', '963', '964', '965', '966', '967', '968', '969', '970', '971', '972', '973', '974', '975', '976', '977', '978', '979', '980', '981', '982', '983', '984', '985', '986', '987', '988', '989', '990', '991', '992', '993', '994', '995', '996', '997', '998', '999', '1000', '1001', '1002', '1003', '1004', '1005', '1006', '1007', '1008', '1009', '1010', '1011', '1012', '1013', '1014', '1015', '1016', '1017', '1018', '1019', '1020', '1021', '1022', '1023', '1024', '1025', '1026', '1027', '1028', '1029', '1030', '1031', '1032', '1033', '1034', '1035', '1036', '1037', '1038', '1039', '1040', '1041', '1042', '1043', '1044', '1045', '1046', '1047', '1048', '1049', '1050', '1051', '1052', '1053', '1054', '1055', '1056', '1057', '1058', '1059', '1060', '1061', '1062', '1063', '1064', '1065', '1066', '1067', '1068', '1069', '1070', '1071', '1072', '1073', '1074', '1075', '1076', '1077', '1078', '1079', '1080', '1081', '1082', '1083', '1084', '1085', '1086', '1087', '1088', '1089', '1090', '1091', '1092', '1093', '1094', '1095', '1096', '1097', '1098', '1099', '1100', '1101', '1102', '1103', '1104', '1105', '1106', '1107', '1108', '1109', '1110', '1111', '1112', '1113', '1114', '1115', '1116', '1117', '1118', '1119', '1120', '1121', '1122', '1123', '1124', '1125', '1126', '1127', '1128', '1129', '1130', '1131', '1132', '1133', '1134', '1135', '1136', '1137', '1138', '1139', '1140', '1141', '1142', '1143', '1144', '1145', '1146', '1147', '1148', '1149', '1150', '1151', '1152', '1153', '1154', '1155', '1156', '1157', '1158', '1159', '1160', '1161', '1162', '1163', '1164', '1165', '1166', '1167', '1168', '1169', '1170', '1171', '1172', '1173', '1174', '1175', '1176', '1177', '1178', '1179', '1180', '1181', '1182', '1183', '1184', '1185', '1186', '1187', '1188', '1189', '1190', '1191', '1192', '1193', '1194', '1195', '1196', '1197', '1198', '1199', '1200', '1201', '1202', '1203', '1204', '1205', '1206', '1207', '1208', '1209', '1210', '1211', '1212', '1213', '1214', '1215', '1216', '1217', '1218', '1219', '1220', '1221', '1222', '1223', '1224', '1225', '1226', '1227', '1228', '1229', '1230', '1231', '1232', '1233', '1234', '1235', '1236', '1237', '1238', '1239', '1240', '1241', '1242', '1243', '1244', '1245', '1246', '1247', '1248', '1249', '1250', '1251', '1252', '1253', '1254', '1255', '1256', '1257', '1258', '1259', '1260', '1261', '1262', '1263', '1264', '1265', '1266', '1267', '1268', '1269', '1270', '1271', '1272', '1273', '1274', '1275', '1276', '1277', '1278', '1279', '0_was_nan', '1_was_nan', '2_was_nan', '3_was_nan', '4_was_nan', '5_was_nan', '6_was_nan', '7_was_nan', '8_was_nan', '9_was_nan', '10_was_nan', '11_was_nan', '12_was_nan', '13_was_nan', '14_was_nan', '15_was_nan', '16_was_nan', '17_was_nan', '18_was_nan', '19_was_nan', '20_was_nan', '21_was_nan', '22_was_nan', '23_was_nan', '24_was_nan', '25_was_nan', '26_was_nan', '27_was_nan', '28_was_nan', '29_was_nan', '30_was_nan', '31_was_nan', '32_was_nan', '33_was_nan', '34_was_nan', '35_was_nan', '36_was_nan', '37_was_nan', '38_was_nan', '39_was_nan', '40_was_nan', '41_was_nan', '42_was_nan', '43_was_nan', '44_was_nan', '45_was_nan', '46_was_nan', '47_was_nan', '48_was_nan', '49_was_nan', '50_was_nan', '51_was_nan', '52_was_nan', '53_was_nan', '54_was_nan', '55_was_nan', '56_was_nan', '57_was_nan', '58_was_nan', '59_was_nan', '60_was_nan', '61_was_nan', '62_was_nan', '63_was_nan', '64_was_nan', '65_was_nan', '66_was_nan', '67_was_nan', '68_was_nan', '69_was_nan', '70_was_nan', '71_was_nan', '72_was_nan', '73_was_nan', '74_was_nan', '75_was_nan', '76_was_nan', '77_was_nan', '78_was_nan', '79_was_nan', '80_was_nan', '81_was_nan', '82_was_nan', '83_was_nan', '84_was_nan', '85_was_nan', '86_was_nan', '87_was_nan', '88_was_nan', '89_was_nan', '90_was_nan', '91_was_nan', '92_was_nan', '93_was_nan', '94_was_nan', '95_was_nan', '96_was_nan', '97_was_nan', '98_was_nan', '99_was_nan', '100_was_nan', '101_was_nan', '102_was_nan', '103_was_nan', '104_was_nan', '105_was_nan', '106_was_nan', '107_was_nan', '108_was_nan', '109_was_nan', '110_was_nan', '111_was_nan', '112_was_nan', '113_was_nan', '114_was_nan', '115_was_nan', '116_was_nan', '117_was_nan', '118_was_nan', '119_was_nan', '120_was_nan', '121_was_nan', '122_was_nan', '123_was_nan', '124_was_nan', '125_was_nan', '126_was_nan', '127_was_nan', '128_was_nan', '129_was_nan', '130_was_nan', '131_was_nan', '132_was_nan', '133_was_nan', '134_was_nan', '135_was_nan', '136_was_nan', '137_was_nan', '138_was_nan', '139_was_nan', '140_was_nan', '141_was_nan', '142_was_nan', '143_was_nan', '144_was_nan', '145_was_nan', '146_was_nan', '147_was_nan', '148_was_nan', '149_was_nan', '150_was_nan', '151_was_nan', '152_was_nan', '153_was_nan', '154_was_nan', '155_was_nan', '156_was_nan', '157_was_nan', '158_was_nan', '159_was_nan', '160_was_nan', '161_was_nan', '162_was_nan', '163_was_nan', '164_was_nan', '165_was_nan', '166_was_nan', '167_was_nan', '168_was_nan', '169_was_nan', '170_was_nan', '171_was_nan', '172_was_nan', '173_was_nan', '174_was_nan', '175_was_nan', '176_was_nan', '177_was_nan', '178_was_nan', '179_was_nan', '180_was_nan', '181_was_nan', '182_was_nan', '183_was_nan', '184_was_nan', '185_was_nan', '186_was_nan', '187_was_nan', '188_was_nan', '189_was_nan', '190_was_nan', '191_was_nan', '192_was_nan', '193_was_nan', '194_was_nan', '195_was_nan', '196_was_nan', '197_was_nan', '198_was_nan', '199_was_nan', '200_was_nan', '201_was_nan', '202_was_nan', '203_was_nan', '204_was_nan', '205_was_nan', '206_was_nan', '207_was_nan', '208_was_nan', '209_was_nan', '210_was_nan', '211_was_nan', '212_was_nan', '213_was_nan', '214_was_nan', '215_was_nan', '216_was_nan', '217_was_nan', '218_was_nan', '219_was_nan', '220_was_nan', '221_was_nan', '222_was_nan', '223_was_nan', '224_was_nan', '225_was_nan', '226_was_nan', '227_was_nan', '228_was_nan', '229_was_nan', '230_was_nan', '231_was_nan', '232_was_nan', '233_was_nan', '234_was_nan', '235_was_nan', '236_was_nan', '237_was_nan', '238_was_nan', '239_was_nan', '240_was_nan', '241_was_nan', '242_was_nan', '243_was_nan', '244_was_nan', '245_was_nan', '246_was_nan', '247_was_nan', '248_was_nan', '249_was_nan', '250_was_nan', '251_was_nan', '252_was_nan', '253_was_nan', '254_was_nan', '255_was_nan', '256_was_nan', '257_was_nan', '258_was_nan', '259_was_nan', '260_was_nan', '261_was_nan', '262_was_nan', '263_was_nan', '264_was_nan', '265_was_nan', '266_was_nan', '267_was_nan', '268_was_nan', '269_was_nan', '270_was_nan', '271_was_nan', '272_was_nan', '273_was_nan', '274_was_nan', '275_was_nan', '276_was_nan', '277_was_nan', '278_was_nan', '279_was_nan', '280_was_nan', '281_was_nan', '282_was_nan', '283_was_nan', '284_was_nan', '285_was_nan', '286_was_nan', '287_was_nan', '288_was_nan', '289_was_nan', '290_was_nan', '291_was_nan', '292_was_nan', '293_was_nan', '294_was_nan', '295_was_nan', '296_was_nan', '297_was_nan', '298_was_nan', '299_was_nan', '300_was_nan', '301_was_nan', '302_was_nan', '303_was_nan', '304_was_nan', '305_was_nan', '306_was_nan', '307_was_nan', '308_was_nan', '309_was_nan', '310_was_nan', '311_was_nan', '312_was_nan', '313_was_nan', '314_was_nan', '315_was_nan', '316_was_nan', '317_was_nan', '318_was_nan', '319_was_nan', '320_was_nan', '321_was_nan', '322_was_nan', '323_was_nan', '324_was_nan', '325_was_nan', '326_was_nan', '327_was_nan', '328_was_nan', '329_was_nan', '330_was_nan', '331_was_nan', '332_was_nan', '333_was_nan', '334_was_nan', '335_was_nan', '336_was_nan', '337_was_nan', '338_was_nan', '339_was_nan', '340_was_nan', '341_was_nan', '342_was_nan', '343_was_nan', '344_was_nan', '345_was_nan', '346_was_nan', '347_was_nan', '348_was_nan', '349_was_nan', '350_was_nan', '351_was_nan', '352_was_nan', '353_was_nan', '354_was_nan', '355_was_nan', '356_was_nan', '357_was_nan', '358_was_nan', '359_was_nan', '360_was_nan', '361_was_nan', '362_was_nan', '363_was_nan', '364_was_nan', '365_was_nan', '366_was_nan', '367_was_nan', '368_was_nan', '369_was_nan', '370_was_nan', '371_was_nan', '372_was_nan', '373_was_nan', '374_was_nan', '375_was_nan', '376_was_nan', '377_was_nan', '378_was_nan', '379_was_nan', '380_was_nan', '381_was_nan', '382_was_nan', '383_was_nan', '384_was_nan', '385_was_nan', '386_was_nan', '387_was_nan', '388_was_nan', '389_was_nan', '390_was_nan', '391_was_nan', '392_was_nan', '393_was_nan', '394_was_nan', '395_was_nan', '396_was_nan', '397_was_nan', '398_was_nan', '399_was_nan', '400_was_nan', '401_was_nan', '402_was_nan', '403_was_nan', '404_was_nan', '405_was_nan', '406_was_nan', '407_was_nan', '408_was_nan', '409_was_nan', '410_was_nan', '411_was_nan', '412_was_nan', '413_was_nan', '414_was_nan', '415_was_nan', '416_was_nan', '417_was_nan', '418_was_nan', '419_was_nan', '420_was_nan', '421_was_nan', '422_was_nan', '423_was_nan', '424_was_nan', '425_was_nan', '426_was_nan', '427_was_nan', '428_was_nan', '429_was_nan', '430_was_nan', '431_was_nan', '432_was_nan', '433_was_nan', '434_was_nan', '435_was_nan', '436_was_nan', '437_was_nan', '438_was_nan', '439_was_nan', '440_was_nan', '441_was_nan', '442_was_nan', '443_was_nan', '444_was_nan', '445_was_nan', '446_was_nan', '447_was_nan', '448_was_nan', '449_was_nan', '450_was_nan', '451_was_nan', '452_was_nan', '453_was_nan', '454_was_nan', '455_was_nan', '456_was_nan', '457_was_nan', '458_was_nan', '459_was_nan', '460_was_nan', '461_was_nan', '462_was_nan', '463_was_nan', '464_was_nan', '465_was_nan', '466_was_nan', '467_was_nan', '468_was_nan', '469_was_nan', '470_was_nan', '471_was_nan', '472_was_nan', '473_was_nan', '474_was_nan', '475_was_nan', '476_was_nan', '477_was_nan', '478_was_nan', '479_was_nan', '480_was_nan', '481_was_nan', '482_was_nan', '483_was_nan', '484_was_nan', '485_was_nan', '486_was_nan', '487_was_nan', '488_was_nan', '489_was_nan', '490_was_nan', '491_was_nan', '492_was_nan', '493_was_nan', '494_was_nan', '495_was_nan', '496_was_nan', '497_was_nan', '498_was_nan', '499_was_nan', '500_was_nan', '501_was_nan', '502_was_nan', '503_was_nan', '504_was_nan', '505_was_nan', '506_was_nan', '507_was_nan', '508_was_nan', '509_was_nan', '510_was_nan', '511_was_nan', '512_was_nan', '513_was_nan', '514_was_nan', '515_was_nan', '516_was_nan', '517_was_nan', '518_was_nan', '519_was_nan', '520_was_nan', '521_was_nan', '522_was_nan', '523_was_nan', '524_was_nan', '525_was_nan', '526_was_nan', '527_was_nan', '528_was_nan', '529_was_nan', '530_was_nan', '531_was_nan', '532_was_nan', '533_was_nan', '534_was_nan', '535_was_nan', '536_was_nan', '537_was_nan', '538_was_nan', '539_was_nan', '540_was_nan', '541_was_nan', '542_was_nan', '543_was_nan', '544_was_nan', '545_was_nan', '546_was_nan', '547_was_nan', '548_was_nan', '549_was_nan', '550_was_nan', '551_was_nan', '552_was_nan', '553_was_nan', '554_was_nan', '555_was_nan', '556_was_nan', '557_was_nan', '558_was_nan', '559_was_nan', '560_was_nan', '561_was_nan', '562_was_nan', '563_was_nan', '564_was_nan', '565_was_nan', '566_was_nan', '567_was_nan', '568_was_nan', '569_was_nan', '570_was_nan', '571_was_nan', '572_was_nan', '573_was_nan', '574_was_nan', '575_was_nan', '576_was_nan', '577_was_nan', '578_was_nan', '579_was_nan', '580_was_nan', '581_was_nan', '582_was_nan', '583_was_nan', '584_was_nan', '585_was_nan', '586_was_nan', '587_was_nan', '588_was_nan', '589_was_nan', '590_was_nan', '591_was_nan', '592_was_nan', '593_was_nan', '594_was_nan', '595_was_nan', '596_was_nan', '597_was_nan', '598_was_nan', '599_was_nan', '600_was_nan', '601_was_nan', '602_was_nan', '603_was_nan', '604_was_nan', '605_was_nan', '606_was_nan', '607_was_nan', '608_was_nan', '609_was_nan', '610_was_nan', '611_was_nan', '612_was_nan', '613_was_nan', '614_was_nan', '615_was_nan', '616_was_nan', '617_was_nan', '618_was_nan', '619_was_nan', '620_was_nan', '621_was_nan', '622_was_nan', '623_was_nan', '624_was_nan', '625_was_nan', '626_was_nan', '627_was_nan', '628_was_nan', '629_was_nan', '630_was_nan', '631_was_nan', '632_was_nan', '633_was_nan', '634_was_nan', '635_was_nan', '636_was_nan', '637_was_nan', '638_was_nan', '639_was_nan', '640_was_nan', '641_was_nan', '642_was_nan', '643_was_nan', '644_was_nan', '645_was_nan', '646_was_nan', '647_was_nan', '648_was_nan', '649_was_nan', '650_was_nan', '651_was_nan', '652_was_nan', '653_was_nan', '654_was_nan', '655_was_nan', '656_was_nan', '657_was_nan', '658_was_nan', '659_was_nan', '660_was_nan', '661_was_nan', '662_was_nan', '663_was_nan', '664_was_nan', '665_was_nan', '666_was_nan', '667_was_nan', '668_was_nan', '669_was_nan', '670_was_nan', '671_was_nan', '672_was_nan', '673_was_nan', '674_was_nan', '675_was_nan', '676_was_nan', '677_was_nan', '678_was_nan', '679_was_nan', '680_was_nan', '681_was_nan', '682_was_nan', '683_was_nan', '684_was_nan', '685_was_nan', '686_was_nan', '687_was_nan', '688_was_nan', '689_was_nan', '690_was_nan', '691_was_nan', '692_was_nan', '693_was_nan', '694_was_nan', '695_was_nan', '696_was_nan', '697_was_nan', '698_was_nan', '699_was_nan', '700_was_nan', '701_was_nan', '702_was_nan', '703_was_nan', '704_was_nan', '705_was_nan', '706_was_nan', '707_was_nan', '708_was_nan', '709_was_nan', '710_was_nan', '711_was_nan', '712

In [2]:
import pandas as pd

final = pd.read_csv("../../ligand_mutation_with_labels_heuristic.csv")
print(final.columns.tolist())

['MW', 'logP', 'H_donors', 'H_acceptors', 'RotatableBonds', 'TPSA', 'FP_0', 'FP_1', 'FP_2', 'FP_3', 'FP_4', 'FP_5', 'FP_6', 'FP_7', 'FP_8', 'FP_9', 'FP_10', 'FP_11', 'FP_12', 'FP_13', 'FP_14', 'FP_15', 'FP_16', 'FP_17', 'FP_18', 'FP_19', 'FP_20', 'FP_21', 'FP_22', 'FP_23', 'FP_24', 'FP_25', 'FP_26', 'FP_27', 'FP_28', 'FP_29', 'FP_30', 'FP_31', 'FP_32', 'FP_33', 'FP_34', 'FP_35', 'FP_36', 'FP_37', 'FP_38', 'FP_39', 'FP_40', 'FP_41', 'FP_42', 'FP_43', 'FP_44', 'FP_45', 'FP_46', 'FP_47', 'FP_48', 'FP_49', 'FP_50', 'FP_51', 'FP_52', 'FP_53', 'FP_54', 'FP_55', 'FP_56', 'FP_57', 'FP_58', 'FP_59', 'FP_60', 'FP_61', 'FP_62', 'FP_63', 'FP_64', 'FP_65', 'FP_66', 'FP_67', 'FP_68', 'FP_69', 'FP_70', 'FP_71', 'FP_72', 'FP_73', 'FP_74', 'FP_75', 'FP_76', 'FP_77', 'FP_78', 'FP_79', 'FP_80', 'FP_81', 'FP_82', 'FP_83', 'FP_84', 'FP_85', 'FP_86', 'FP_87', 'FP_88', 'FP_89', 'FP_90', 'FP_91', 'FP_92', 'FP_93', 'FP_94', 'FP_95', 'FP_96', 'FP_97', 'FP_98', 'FP_99', 'FP_100', 'FP_101', 'FP_102', 'FP_103', 'FP_104', 'FP_105', 'FP_106', 'FP_107', 'FP_108', 'FP_109', 'FP_110', 'FP_111', 'FP_112', 'FP_113', 'FP_114', 'FP_115', 'FP_116', 'FP_117', 'FP_118', 'FP_119', 'FP_120', 'FP_121', 'FP_122', 'FP_123', 'FP_124', 'FP_125', 'FP_126', 'FP_127', 'FP_128', 'FP_129', 'FP_130', 'FP_131', 'FP_132', 'FP_133', 'FP_134', 'FP_135', 'FP_136', 'FP_137', 'FP_138', 'FP_139', 'FP_140', 'FP_141', 'FP_142', 'FP_143', 'FP_144', 'FP_145', 'FP_146', 'FP_147', 'FP_148', 'FP_149', 'FP_150', 'FP_151', 'FP_152', 'FP_153', 'FP_154', 'FP_155', 'FP_156', 'FP_157', 'FP_158', 'FP_159', 'FP_160', 'FP_161', 'FP_162', 'FP_163', 'FP_164', 'FP_165', 'FP_166', 'FP_167', 'FP_168', 'FP_169', 'FP_170', 'FP_171', 'FP_172', 'FP_173', 'FP_174', 'FP_175', 'FP_176', 'FP_177', 'FP_178', 'FP_179', 'FP_180', 'FP_181', 'FP_182', 'FP_183', 'FP_184', 'FP_185', 'FP_186', 'FP_187', 'FP_188', 'FP_189', 'FP_190', 'FP_191', 'FP_192', 'FP_193', 'FP_194', 'FP_195', 'FP_196', 'FP_197', 'FP_198', 'FP_199', 'FP_200', 'FP_201', 'FP_202', 'FP_203', 'FP_204', 'FP_205', 'FP_206', 'FP_207', 'FP_208', 'FP_209', 'FP_210', 'FP_211', 'FP_212', 'FP_213', 'FP_214', 'FP_215', 'FP_216', 'FP_217', 'FP_218', 'FP_219', 'FP_220', 'FP_221', 'FP_222', 'FP_223', 'FP_224', 'FP_225', 'FP_226', 'FP_227', 'FP_228', 'FP_229', 'FP_230', 'FP_231', 'FP_232', 'FP_233', 'FP_234', 'FP_235', 'FP_236', 'FP_237', 'FP_238', 'FP_239', 'FP_240', 'FP_241', 'FP_242', 'FP_243', 'FP_244', 'FP_245', 'FP_246', 'FP_247', 'FP_248', 'FP_249', 'FP_250', 'FP_251', 'FP_252', 'FP_253', 'FP_254', 'FP_255', 'FP_256', 'FP_257', 'FP_258', 'FP_259', 'FP_260', 'FP_261', 'FP_262', 'FP_263', 'FP_264', 'FP_265', 'FP_266', 'FP_267', 'FP_268', 'FP_269', 'FP_270', 'FP_271', 'FP_272', 'FP_273', 'FP_274', 'FP_275', 'FP_276', 'FP_277', 'FP_278', 'FP_279', 'FP_280', 'FP_281', 'FP_282', 'FP_283', 'FP_284', 'FP_285', 'FP_286', 'FP_287', 'FP_288', 'FP_289', 'FP_290', 'FP_291', 'FP_292', 'FP_293', 'FP_294', 'FP_295', 'FP_296', 'FP_297', 'FP_298', 'FP_299', 'FP_300', 'FP_301', 'FP_302', 'FP_303', 'FP_304', 'FP_305', 'FP_306', 'FP_307', 'FP_308', 'FP_309', 'FP_310', 'FP_311', 'FP_312', 'FP_313', 'FP_314', 'FP_315', 'FP_316', 'FP_317', 'FP_318', 'FP_319', 'FP_320', 'FP_321', 'FP_322', 'FP_323', 'FP_324', 'FP_325', 'FP_326', 'FP_327', 'FP_328', 'FP_329', 'FP_330', 'FP_331', 'FP_332', 'FP_333', 'FP_334', 'FP_335', 'FP_336', 'FP_337', 'FP_338', 'FP_339', 'FP_340', 'FP_341', 'FP_342', 'FP_343', 'FP_344', 'FP_345', 'FP_346', 'FP_347', 'FP_348', 'FP_349', 'FP_350', 'FP_351', 'FP_352', 'FP_353', 'FP_354', 'FP_355', 'FP_356', 'FP_357', 'FP_358', 'FP_359', 'FP_360', 'FP_361', 'FP_362', 'FP_363', 'FP_364', 'FP_365', 'FP_366', 'FP_367', 'FP_368', 'FP_369', 'FP_370', 'FP_371', 'FP_372', 'FP_373', 'FP_374', 'FP_375', 'FP_376', 'FP_377', 'FP_378', 'FP_379', 'FP_380', 'FP_381', 'FP_382', 'FP_383', 'FP_384', 'FP_385', 'FP_386', 'FP_387', 'FP_388', 'FP_389', 'FP_390', 'FP_391', 'FP_392', 'FP_393', 'FP_394', 'FP_395', 'FP_396', 'FP_397', 'FP_398', 'FP_399', 'FP_400', 'FP_401', 'FP_402', 'FP_403', 'FP_404', 'FP_405', 'FP_406', 'FP_407', 'FP_408', 'FP_409', 'FP_410', 'FP_411', 'FP_412', 'FP_413', 'FP_414', 'FP_415', 'FP_416', 'FP_417', 'FP_418', 'FP_419', 'FP_420', 'FP_421', 'FP_422', 'FP_423', 'FP_424', 'FP_425', 'FP_426', 'FP_427', 'FP_428', 'FP_429', 'FP_430', 'FP_431', 'FP_432', 'FP_433', 'FP_434', 'FP_435', 'FP_436', 'FP_437', 'FP_438', 'FP_439', 'FP_440', 'FP_441', 'FP_442', 'FP_443', 'FP_444', 'FP_445', 'FP_446', 'FP_447', 'FP_448', 'FP_449', 'FP_450', 'FP_451', 'FP_452', 'FP_453', 'FP_454', 'FP_455', 'FP_456', 'FP_457', 'FP_458', 'FP_459', 'FP_460', 'FP_461', 'FP_462', 'FP_463', 'FP_464', 'FP_465', 'FP_466', 'FP_467', 'FP_468', 'FP_469', 'FP_470', 'FP_471', 'FP_472', 'FP_473', 'FP_474', 'FP_475', 'FP_476', 'FP_477', 'FP_478', 'FP_479', 'FP_480', 'FP_481', 'FP_482', 'FP_483', 'FP_484', 'FP_485', 'FP_486', 'FP_487', 'FP_488', 'FP_489', 'FP_490', 'FP_491', 'FP_492', 'FP_493', 'FP_494', 'FP_495', 'FP_496', 'FP_497', 'FP_498', 'FP_499', 'FP_500', 'FP_501', 'FP_502', 'FP_503', 'FP_504', 'FP_505', 'FP_506', 'FP_507', 'FP_508', 'FP_509', 'FP_510', 'FP_511', 'FP_512', 'FP_513', 'FP_514', 'FP_515', 'FP_516', 'FP_517', 'FP_518', 'FP_519', 'FP_520', 'FP_521', 'FP_522', 'FP_523', 'FP_524', 'FP_525', 'FP_526', 'FP_527', 'FP_528', 'FP_529', 'FP_530', 'FP_531', 'FP_532', 'FP_533', 'FP_534', 'FP_535', 'FP_536', 'FP_537', 'FP_538', 'FP_539', 'FP_540', 'FP_541', 'FP_542', 'FP_543', 'FP_544', 'FP_545', 'FP_546', 'FP_547', 'FP_548', 'FP_549', 'FP_550', 'FP_551', 'FP_552', 'FP_553', 'FP_554', 'FP_555', 'FP_556', 'FP_557', 'FP_558', 'FP_559', 'FP_560', 'FP_561', 'FP_562', 'FP_563', 'FP_564', 'FP_565', 'FP_566', 'FP_567', 'FP_568', 'FP_569', 'FP_570', 'FP_571', 'FP_572', 'FP_573', 'FP_574', 'FP_575', 'FP_576', 'FP_577', 'FP_578', 'FP_579', 'FP_580', 'FP_581', 'FP_582', 'FP_583', 'FP_584', 'FP_585', 'FP_586', 'FP_587', 'FP_588', 'FP_589', 'FP_590', 'FP_591', 'FP_592', 'FP_593', 'FP_594', 'FP_595', 'FP_596', 'FP_597', 'FP_598', 'FP_599', 'FP_600', 'FP_601', 'FP_602', 'FP_603', 'FP_604', 'FP_605', 'FP_606', 'FP_607', 'FP_608', 'FP_609', 'FP_610', 'FP_611', 'FP_612', 'FP_613', 'FP_614', 'FP_615', 'FP_616', 'FP_617', 'FP_618', 'FP_619', 'FP_620', 'FP_621', 'FP_622', 'FP_623', 'FP_624', 'FP_625', 'FP_626', 'FP_627', 'FP_628', 'FP_629', 'FP_630', 'FP_631', 'FP_632', 'FP_633', 'FP_634', 'FP_635', 'FP_636', 'FP_637', 'FP_638', 'FP_639', 'FP_640', 'FP_641', 'FP_642', 'FP_643', 'FP_644', 'FP_645', 'FP_646', 'FP_647', 'FP_648', 'FP_649', 'FP_650', 'FP_651', 'FP_652', 'FP_653', 'FP_654', 'FP_655', 'FP_656', 'FP_657', 'FP_658', 'FP_659', 'FP_660', 'FP_661', 'FP_662', 'FP_663', 'FP_664', 'FP_665', 'FP_666', 'FP_667', 'FP_668', 'FP_669', 'FP_670', 'FP_671', 'FP_672', 'FP_673', 'FP_674', 'FP_675', 'FP_676', 'FP_677', 'FP_678', 'FP_679', 'FP_680', 'FP_681', 'FP_682', 'FP_683', 'FP_684', 'FP_685', 'FP_686', 'FP_687', 'FP_688', 'FP_689', 'FP_690', 'FP_691', 'FP_692', 'FP_693', 'FP_694', 'FP_695', 'FP_696', 'FP_697', 'FP_698', 'FP_699', 'FP_700', 'FP_701', 'FP_702', 'FP_703', 'FP_704', 'FP_705', 'FP_706', 'FP_707', 'FP_708', 'FP_709', 'FP_710', 'FP_711', 'FP_712', 'FP_713', 'FP_714', 'FP_715', 'FP_716', 'FP_717', 'FP_718', 'FP_719', 'FP_720', 'FP_721', 'FP_722', 'FP_723', 'FP_724', 'FP_725', 'FP_726', 'FP_727', 'FP_728', 'FP_729', 'FP_730', 'FP_731', 'FP_732', 'FP_733', 'FP_734', 'FP_735', 'FP_736', 'FP_737', 'FP_738', 'FP_739', 'FP_740', 'FP_741', 'FP_742', 'FP_743', 'FP_744', 'FP_745', 'FP_746', 'FP_747', 'FP_748', 'FP_749', 'FP_750', 'FP_751', 'FP_752', 'FP_753', 'FP_754', 'FP_755', 'FP_756', 'FP_757', 'FP_758', 'FP_759', 'FP_760', 'FP_761', 'FP_762', 'FP_763', 'FP_764', 'FP_765', 'FP_766', 'FP_767', 'FP_768', 'FP_769', 'FP_770', 'FP_771', 'FP_772', 'FP_773', 'FP_774', 'FP_775', 'FP_776', 'FP_777', 'FP_778', 'FP_779', 'FP_780', 'FP_781', 'FP_782', 'FP_783', 'FP_784', 'FP_785', 'FP_786', 'FP_787', 'FP_788', 'FP_789', 'FP_790', 'FP_791', 'FP_792', 'FP_793', 'FP_794', 'FP_795', 'FP_796', 'FP_797', 'FP_798', 'FP_799', 'FP_800', 'FP_801', 'FP_802', 'FP_803', 'FP_804', 'FP_805', 'FP_806', 'FP_807', 'FP_808', 'FP_809', 'FP_810', 'FP_811', 'FP_812', 'FP_813', 'FP_814', 'FP_815', 'FP_816', 'FP_817', 'FP_818', 'FP_819', 'FP_820', 'FP_821', 'FP_822', 'FP_823', 'FP_824', 'FP_825', 'FP_826', 'FP_827', 'FP_828', 'FP_829', 'FP_830', 'FP_831', 'FP_832', 'FP_833', 'FP_834', 'FP_835', 'FP_836', 'FP_837', 'FP_838', 'FP_839', 'FP_840', 'FP_841', 'FP_842', 'FP_843', 'FP_844', 'FP_845', 'FP_846', 'FP_847', 'FP_848', 'FP_849', 'FP_850', 'FP_851', 'FP_852', 'FP_853', 'FP_854', 'FP_855', 'FP_856', 'FP_857', 'FP_858', 'FP_859', 'FP_860', 'FP_861', 'FP_862', 'FP_863', 'FP_864', 'FP_865', 'FP_866', 'FP_867', 'FP_868', 'FP_869', 'FP_870', 'FP_871', 'FP_872', 'FP_873', 'FP_874', 'FP_875', 'FP_876', 'FP_877', 'FP_878', 'FP_879', 'FP_880', 'FP_881', 'FP_882', 'FP_883', 'FP_884', 'FP_885', 'FP_886', 'FP_887', 'FP_888', 'FP_889', 'FP_890', 'FP_891', 'FP_892', 'FP_893', 'FP_894', 'FP_895', 'FP_896', 'FP_897', 'FP_898', 'FP_899', 'FP_900', 'FP_901', 'FP_902', 'FP_903', 'FP_904', 'FP_905', 'FP_906', 'FP_907', 'FP_908', 'FP_909', 'FP_910', 'FP_911', 'FP_912', 'FP_913', 'FP_914', 'FP_915', 'FP_916', 'FP_917', 'FP_918', 'FP_919', 'FP_920', 'FP_921', 'FP_922', 'FP_923', 'FP_924', 'FP_925', 'FP_926', 'FP_927', 'FP_928', 'FP_929', 'FP_930', 'FP_931', 'FP_932', 'FP_933', 'FP_934', 'FP_935', 'FP_936', 'FP_937', 'FP_938', 'FP_939', 'FP_940', 'FP_941', 'FP_942', 'FP_943', 'FP_944', 'FP_945', 'FP_946', 'FP_947', 'FP_948', 'FP_949', 'FP_950', 'FP_951', 'FP_952', 'FP_953', 'FP_954', 'FP_955', 'FP_956', 'FP_957', 'FP_958', 'FP_959', 'FP_960', 'FP_961', 'FP_962', 'FP_963', 'FP_964', 'FP_965', 'FP_966', 'FP_967', 'FP_968', 'FP_969', 'FP_970', 'FP_971', 'FP_972', 'FP_973', 'FP_974', 'FP_975', 'FP_976', 'FP_977', 'FP_978', 'FP_979', 'FP_980', 'FP_981', 'FP_982', 'FP_983', 'FP_984', 'FP_985', 'FP_986', 'FP_987', 'FP_988', 'FP_989', 'FP_990', 'FP_991', 'FP_992', 'FP_993', 'FP_994', 'FP_995', 'FP_996', 'FP_997', 'FP_998', 'FP_999', 'FP_1000', 'FP_1001', 'FP_1002', 'FP_1003', 'FP_1004', 'FP_1005', 'FP_1006', 'FP_1007', 'FP_1008', 'FP_1009', 'FP_1010', 'FP_1011', 'FP_1012', 'FP_1013', 'FP_1014', 'FP_1015', 'FP_1016', 'FP_1017', 'FP_1018', 'FP_1019', 'FP_1020', 'FP_1021', 'FP_1022', 'FP_1023', 'AvgHydro', 'StdHydro', 'FracPolar', 'FracCharge', 'FracAromatic', 'PocketSize', 'LigandName', 'Mutation', 'LigandCID', 'DockingScore_WT', 'Delta_AvgHydro', 'Delta_Charge', 'DockingScore_label']

In [1]:
import pandas as pd
files = {
    "labels": "../../data/processed/labels.csv",
    "seq_features": "../../data/processed/seq_features.csv",
    "embeddings": "../../data/processed/embeddings.csv",
    "context_features": "../../data/processed/context_features.csv",
}
datacols = {name: pd.read_csv(path).columns.tolist() for name, path in files.items()}
for name, cols in datacols.items():
    print(f"{name} columns ({len(cols)}): {cols}\n")

labels columns (14): ['site_RBD', 'site_SARS2', 'wildtype', 'mutant', 'mutation', 'mutation_RBD', 'bind_lib1', 'bind_lib2', 'ace2_score', 'expr_lib1', 'expr_lib2', 'expr_score', 'mut_id', 'label']

seq_features columns (11): ['mut_id', 'pos', 'wt', 'mut', 'blosum62', 'grantham', 'delta_charge', 'delta_hydro', 'delta_volume', 'delta_polarity', 'is_stop']

embeddings columns (1281): ['mut_id', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31', '32', '33', '34', '35', '36', '37', '38', '39', '40', '41', '42', '43', '44', '45', '46', '47', '48', '49', '50', '51', '52', '53', '54', '55', '56', '57', '58', '59', '60', '61', '62', '63', '64', '65', '66', '67', '68', '69', '70', '71', '72', '73', '74', '75', '76', '77', '78', '79', '80', '81', '82', '83', '84', '85', '86', '87', '88', '89', '90', '91', '92', '93', '94', '95', '96', '97', '98', '99', '100', '101', '102', '103', '104', '105', '106', '107', '108', '109', '110', '111', '112', '113', '114', '115', '116', '117', '118', '119', '120', '121', '122', '123', '124', '125', '126', '127', '128', '129', '130', '131', '132', '133', '134', '135', '136', '137', '138', '139', '140', '141', '142', '143', '144', '145', '146', '147', '148', '149', '150', '151', '152', '153', '154', '155', '156', '157', '158', '159', '160', '161', '162', '163', '164', '165', '166', '167', '168', '169', '170', '171', '172', '173', '174', '175', '176', '177', '178', '179', '180', '181', '182', '183', '184', '185', '186', '187', '188', '189', '190', '191', '192', '193', '194', '195', '196', '197', '198', '199', '200', '201', '202', '203', '204', '205', '206', '207', '208', '209', '210', '211', '212', '213', '214', '215', '216', '217', '218', '219', '220', '221', '222', '223', '224', '225', '226', '227', '228', '229', '230', '231', '232', '233', '234', '235', '236', '237', '238', '239', '240', '241', '242', '243', '244', '245', '246', '247', '248', '249', '250', '251', '252', '253', '254', '255', '256', '257', '258', '259', '260', '261', '262', '263', '264', '265', '266', '267', '268', '269', '270', '271', '272', '273', '274', '275', '276', '277', '278', '279', '280', '281', '282', '283', '284', '285', '286', '287', '288', '289', '290', '291', '292', '293', '294', '295', '296', '297', '298', '299', '300', '301', '302', '303', '304', '305', '306', '307', '308', '309', '310', '311', '312', '313', '314', '315', '316', '317', '318', '319', '320', '321', '322', '323', '324', '325', '326', '327', '328', '329', '330', '331', '332', '333', '334', '335', '336', '337', '338', '339', '340', '341', '342', '343', '344', '345', '346', '347', '348', '349', '350', '351', '352', '353', '354', '355', '356', '357', '358', '359', '360', '361', '362', '363', '364', '365', '366', '367', '368', '369', '370', '371', '372', '373', '374', '375', '376', '377', '378', '379', '380', '381', '382', '383', '384', '385', '386', '387', '388', '389', '390', '391', '392', '393', '394', '395', '396', '397', '398', '399', '400', '401', '402', '403', '404', '405', '406', '407', '408', '409', '410', '411', '412', '413', '414', '415', '416', '417', '418', '419', '420', '421', '422', '423', '424', '425', '426', '427', '428', '429', '430', '431', '432', '433', '434', '435', '436', '437', '438', '439', '440', '441', '442', '443', '444', '445', '446', '447', '448', '449', '450', '451', '452', '453', '454', '455', '456', '457', '458', '459', '460', '461', '462', '463', '464', '465', '466', '467', '468', '469', '470', '471', '472', '473', '474', '475', '476', '477', '478', '479', '480', '481', '482', '483', '484', '485', '486', '487', '488', '489', '490', '491', '492', '493', '494', '495', '496', '497', '498', '499', '500', '501', '502', '503', '504', '505', '506', '507', '508', '509', '510', '511', '512', '513', '514', '515', '516', '517', '518', '519', '520', '521', '522', '523', '524', '525', '526', '527', '528', '529', '530', '531', '532', '533', '534', '535', '536', '537', '538', '539', '540', '541', '542', '543', '544', '545', '546', '547', '548', '549', '550', '551', '552', '553', '554', '555', '556', '557', '558', '559', '560', '561', '562', '563', '564', '565', '566', '567', '568', '569', '570', '571', '572', '573', '574', '575', '576', '577', '578', '579', '580', '581', '582', '583', '584', '585', '586', '587', '588', '589', '590', '591', '592', '593', '594', '595', '596', '597', '598', '599', '600', '601', '602', '603', '604', '605', '606', '607', '608', '609', '610', '611', '612', '613', '614', '615', '616', '617', '618', '619', '620', '621', '622', '623', '624', '625', '626', '627', '628', '629', '630', '631', '632', '633', '634', '635', '636', '637', '638', '639', '640', '641', '642', '643', '644', '645', '646', '647', '648', '649', '650', '651', '652', '653', '654', '655', '656', '657', '658', '659', '660', '661', '662', '663', '664', '665', '666', '667', '668', '669', '670', '671', '672', '673', '674', '675', '676', '677', '678', '679', '680', '681', '682', '683', '684', '685', '686', '687', '688', '689', '690', '691', '692', '693', '694', '695', '696', '697', '698', '699', '700', '701', '702', '703', '704', '705', '706', '707', '708', '709', '710', '711', '712', '713', '714', '715', '716', '717', '718', '719', '720', '721', '722', '723', '724', '725', '726', '727', '728', '729', '730', '731', '732', '733', '734', '735', '736', '737', '738', '739', '740', '741', '742', '743', '744', '745', '746', '747', '748', '749', '750', '751', '752', '753', '754', '755', '756', '757', '758', '759', '760', '761', '762', '763', '764', '765', '766', '767', '768', '769', '770', '771', '772', '773', '774', '775', '776', '777', '778', '779', '780', '781', '782', '783', '784', '785', '786', '787', '788', '789', '790', '791', '792', '793', '794', '795', '796', '797', '798', '799', '800', '801', '802', '803', '804', '805', '806', '807', '808', '809', '810', '811', '812', '813', '814', '815', '816', '817', '818', '819', '820', '821', '822', '823', '824', '825', '826', '827', '828', '829', '830', '831', '832', '833', '834', '835', '836', '837', '838', '839', '840', '841', '842', '843', '844', '845', '846', '847', '848', '849', '850', '851', '852', '853', '854', '855', '856', '857', '858', '859', '860', '861', '862', '863', '864', '865', '866', '867', '868', '869', '870', '871', '872', '873', '874', '875', '876', '877', '878', '879', '880', '881', '882', '883', '884', '885', '886', '887', '888', '889', '890', '891', '892', '893', '894', '895', '896', '897', '898', '899', '900', '901', '902', '903', '904', '905', '906', '907', '908', '909', '910', '911', '912', '913', '914', '915', '916', '917', '918', '919', '920', '921', '922', '923', '924', '925', '926', '927', '928', '929', '930', '931', '932', '933', '934', '935', '936', '937', '938', '939', '940', '941', '942', '943', '944', '945', '946', '947', '948', '949', '950', '951', '952', '953', '954', '955', '956', '957', '958', '959', '960', '961', '962', '963', '964', '965', '966', '967', '968', '969', '970', '971', '972', '973', '974', '975', '976', '977', '978', '979', '980', '981', '982', '983', '984', '985', '986', '987', '988', '989', '990', '991', '992', '993', '994', '995', '996', '997', '998', '999', '1000', '1001', '1002', '1003', '1004', '1005', '1006', '1007', '1008', '1009', '1010', '1011', '1012', '1013', '1014', '1015', '1016', '1017', '1018', '1019', '1020', '1021', '1022', '1023', '1024', '1025', '1026', '1027', '1028', '1029', '1030', '1031', '1032', '1033', '1034', '1035', '1036', '1037', '1038', '1039', '1040', '1041', '1042', '1043', '1044', '1045', '1046', '1047', '1048', '1049', '1050', '1051', '1052', '1053', '1054', '1055', '1056', '1057', '1058', '1059', '1060', '1061', '1062', '1063', '1064', '1065', '1066', '1067', '1068', '1069', '1070', '1071', '1072', '1073', '1074', '1075', '1076', '1077', '1078', '1079', '1080', '1081', '1082', '1083', '1084', '1085', '1086', '1087', '1088', '1089', '1090', '1091', '1092', '1093', '1094', '1095', '1096', '1097', '1098', '1099', '1100', '1101', '1102', '1103', '1104', '1105', '1106', '1107', '1108', '1109', '1110', '1111', '1112', '1113', '1114', '1115', '1116', '1117', '1118', '1119', '1120', '1121', '1122', '1123', '1124', '1125', '1126', '1127', '1128', '1129', '1130', '1131', '1132', '1133', '1134', '1135', '1136', '1137', '1138', '1139', '1140', '1141', '1142', '1143', '1144', '1145', '1146', '1147', '1148', '1149', '1150', '1151', '1152', '1153', '1154', '1155', '1156', '1157', '1158', '1159', '1160', '1161', '1162', '1163', '1164', '1165', '1166', '1167', '1168', '1169', '1170', '1171', '1172', '1173', '1174', '1175', '1176', '1177', '1178', '1179', '1180', '1181', '1182', '1183', '1184', '1185', '1186', '1187', '1188', '1189', '1190', '1191', '1192', '1193', '1194', '1195', '1196', '1197', '1198', '1199', '1200', '1201', '1202', '1203', '1204', '1205', '1206', '1207', '1208', '1209', '1210', '1211', '1212', '1213', '1214', '1215', '1216', '1217', '1218', '1219', '1220', '1221', '1222', '1223', '1224', '1225', '1226', '1227', '1228', '1229', '1230', '1231', '1232', '1233', '1234', '1235', '1236', '1237', '1238', '1239', '1240', '1241', '1242', '1243', '1244', '1245', '1246', '1247', '1248', '1249', '1250', '1251', '1252', '1253', '1254', '1255', '1256', '1257', '1258', '1259', '1260', '1261', '1262', '1263', '1264', '1265', '1266', '1267', '1268', '1269', '1270', '1271', '1272', '1273', '1274', '1275', '1276', '1277', '1278', '1279']

context_features columns (11): ['residue', 'aa', 'secondary_structure', 'rsa', 'dist_to_ACE2', 'dist_to_RBM', 'ss_H', 'ss_E', 'ss_T', 'ss_C', 'rsa_norm']

In [2]:
df1 = pd.read_csv("../../data/processed/labels.csv")
df2 = pd.read_csv("../../data/processed/seq_features.csv")
df3 = pd.read_csv("../../data/processed/embeddings.csv")
df4 = pd.read_csv("../../data/processed/context_features.csv")
print("Labels head:", df1.head(3))
print("Seq Features head:", df2.head(3))
print("Embeddings head:", df3.head(3))
print("Context Features head:", df4.head(3))

Labels head:    site_RBD  site_SARS2 wildtype mutant mutation mutation_RBD  bind_lib1  \
0         1         331        N      A    N331A          N1A      -0.05
1         1         331        N      C    N331C          N1C      -0.08
2         1         331        N      D    N331D          N1D       0.00

   bind_lib2  ace2_score  expr_lib1  expr_lib2  expr_score mut_id  label
0      -0.02       -0.03      -0.14      -0.08       -0.11  N331A      1
1      -0.10       -0.09      -1.56      -0.97       -1.26  N331C      0
2       0.07        0.03      -0.75      -0.12       -0.44  N331D      1
Seq Features head:   mut_id  pos wt mut  blosum62  grantham  delta_charge  delta_hydro  \
0  N331A    1  N   A        -2       111             0          5.3
1  N331C    1  N   C        -3       139             0          6.0
2  N331D    1  N   D         1        23            -1          0.0

   delta_volume  delta_polarity  is_stop
0           -26            -3.5        0
1            -6            -6.1        0
2            -3             1.4        0
Embeddings head:   mut_id         0         1         2         3         4         5  \
0  N331A -0.067741  0.199019 -0.179698  0.201105 -0.067334  0.090759
1  N331C -0.064530  0.072357 -0.115226  0.166408 -0.056582  0.087773
2  N331D -0.019751  0.020047 -0.132962  0.280015 -0.045891  0.089194

          6         7         8  ...      1270      1271      1272      1273  \
0  0.039440 -0.037416 -0.094640  ...  0.088068  0.020139  0.111115  0.164220
1  0.107421  0.028012 -0.098189  ... -0.144662  0.109343  0.224311  0.116104
2  0.085321  0.080868 -0.093845  ...  0.040745  0.110557  0.165327  0.120866

       1274      1275      1276      1277      1278      1279
0 -0.012009  0.274097  0.053875 -0.067687 -0.159784  0.017576
1  0.093836  0.178063  0.139208 -0.079412 -0.243861  0.061967
2  0.029265  0.243903  0.033439 -0.036450  0.051138  0.127455

[3 rows x 1281 columns]
Context Features head:    residue aa secondary_structure       rsa  dist_to_ACE2  dist_to_RBM  ss_H  \
0      319  G                   T  0.500000           0.0          119     0
1      320  N                   T  0.993631           0.0          118     0
2      321  V                   T  1.000000           0.0          117     0

   ss_E  ss_T  ss_C  rsa_norm
0     0     1     0  0.500000
1     0     1     0  0.993631
2     0     1     0  1.000000

In [5]:
import pandas as pd

# Load CSVs
labels = pd.read_csv("../../data/processed/labels.csv")
seq_features = pd.read_csv("../../data/processed/seq_features.csv")
embeddings = pd.read_csv("../../data/processed/embeddings.csv")
context = pd.read_csv("../../data/processed/context_features.csv")

# Merge step by step
df = labels.merge(seq_features, on="mut_id", how="left")
df = df.merge(embeddings, on="mut_id", how="left")
df = df.merge(context, left_on="site_SARS2", right_on="residue", how="left")

# Drop duplicate residue column
df.drop(columns=["residue"], inplace=True)

print("Merged dataset shape:", df.shape)
df.head()

Merged dataset shape: (4221, 1314)

,site_RBD,site_SARS2,wildtype,mutant,mutation,mutation_RBD,bind_lib1,bind_lib2,ace2_score,expr_lib1,...,aa,secondary_structure,rsa,dist_to_ACE2,dist_to_RBM,ss_H,ss_E,ss_T,ss_C,rsa_norm
0,1,331,N,A,N331A,N1A,-0.05,-0.02,-0.03,-0.14,...,W,E,0.154185,0.0,107,0,1,0,0,0.154185
1,1,331,N,C,N331C,N1C,-0.08,-0.10,-0.09,-1.56,...,W,E,0.154185,0.0,107,0,1,0,0,0.154185
2,1,331,N,D,N331D,N1D,0.00,0.07,0.03,-0.75,...,W,E,0.154185,0.0,107,0,1,0,0,0.154185
3,1,331,N,E,N331E,N1E,0.02,-0.02,0.00,-0.39,...,W,E,0.154185,0.0,107,0,1,0,0,0.154185
4,1,331,N,F,N331F,N1F,-0.03,-0.16,-0.10,-0.83,...,W,E,0.154185,0.0,107,0,1,0,0,0.154185

In [6]:
df = df[df["is_stop"] == 0].copy()
df

,site_RBD,site_SARS2,wildtype,mutant,mutation,mutation_RBD,bind_lib1,bind_lib2,ace2_score,expr_lib1,...,aa,secondary_structure,rsa,dist_to_ACE2,dist_to_RBM,ss_H,ss_E,ss_T,ss_C,rsa_norm
0,1,331,N,A,N331A,N1A,-0.05,-0.02,-0.03,-0.14,...,W,E,0.154185,0.0,107,0,1,0,0,0.154185
1,1,331,N,C,N331C,N1C,-0.08,-0.10,-0.09,-1.56,...,W,E,0.154185,0.0,107,0,1,0,0,0.154185
2,1,331,N,D,N331D,N1D,0.00,0.07,0.03,-0.75,...,W,E,0.154185,0.0,107,0,1,0,0,0.154185
3,1,331,N,E,N331E,N1E,0.02,-0.02,0.00,-0.39,...,W,E,0.154185,0.0,107,0,1,0,0,0.154185
4,1,331,N,F,N331F,N1F,-0.03,-0.16,-0.10,-0.83,...,W,E,0.154185,0.0,107,0,1,0,0,0.154185
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4215,201,531,T,S,T531S,T201S,0.02,0.00,0.01,0.06,...,E,H,0.608247,0.0,25,1,0,0,0,0.608247
4216,201,531,T,T,T531T,T201T,0.00,0.00,0.00,0.00,...,E,H,0.608247,0.0,25,1,0,0,0,0.608247
4217,201,531,T,V,T531V,T201V,0.03,-0.02,0.01,-0.07,...,E,H,0.608247,0.0,25,1,0,0,0,0.608247
4218,201,531,T,W,T531W,T201W,0.02,-0.06,-0.02,-0.13,...,E,H,0.608247,0.0,25,1,0,0,0,0.608247
4219,201,531,T,Y,T531Y,T201Y,0.00,-0.03,-0.01,-0.03,...,E,H,0.608247,0.0,25,1,0,0,0,0.608247

In [7]:
df = df[df["wildtype"] != df["mutant"]].copy()
df

,site_RBD,site_SARS2,wildtype,mutant,mutation,mutation_RBD,bind_lib1,bind_lib2,ace2_score,expr_lib1,...,aa,secondary_structure,rsa,dist_to_ACE2,dist_to_RBM,ss_H,ss_E,ss_T,ss_C,rsa_norm
0,1,331,N,A,N331A,N1A,-0.05,-0.02,-0.03,-0.14,...,W,E,0.154185,0.0,107,0,1,0,0,0.154185
1,1,331,N,C,N331C,N1C,-0.08,-0.10,-0.09,-1.56,...,W,E,0.154185,0.0,107,0,1,0,0,0.154185
2,1,331,N,D,N331D,N1D,0.00,0.07,0.03,-0.75,...,W,E,0.154185,0.0,107,0,1,0,0,0.154185
3,1,331,N,E,N331E,N1E,0.02,-0.02,0.00,-0.39,...,W,E,0.154185,0.0,107,0,1,0,0,0.154185
4,1,331,N,F,N331F,N1F,-0.03,-0.16,-0.10,-0.83,...,W,E,0.154185,0.0,107,0,1,0,0,0.154185
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4214,201,531,T,R,T531R,T201R,0.03,-0.04,-0.01,-0.06,...,E,H,0.608247,0.0,25,1,0,0,0,0.608247
4215,201,531,T,S,T531S,T201S,0.02,0.00,0.01,0.06,...,E,H,0.608247,0.0,25,1,0,0,0,0.608247
4217,201,531,T,V,T531V,T201V,0.03,-0.02,0.01,-0.07,...,E,H,0.608247,0.0,25,1,0,0,0,0.608247
4218,201,531,T,W,T531W,T201W,0.02,-0.06,-0.02,-0.13,...,E,H,0.608247,0.0,25,1,0,0,0,0.608247
4219,201,531,T,Y,T531Y,T201Y,0.00,-0.03,-0.01,-0.03,...,E,H,0.608247,0.0,25,1,0,0,0,0.608247

In [8]:
df.size
df.shape

(3819, 1314)

In [9]:
# Fill RSA, distances, etc.
structural_cols = ["rsa_norm", "dist_to_ACE2", "dist_to_RBM", "ss_H", "ss_E", "ss_T", "ss_C"]

for col in structural_cols:
    if col in df.columns:
        df[col] = df[col].fillna(0.0)

In [10]:
from sklearn.preprocessing import StandardScaler
import joblib

# Define columns to exclude
exclude_cols = [
    "site_RBD", "site_SARS2", "wildtype", "mutant", "mutation",
    "mutation_RBD", "bind_lib1", "bind_lib2", "ace2_score",
    "expr_lib1", "expr_lib2", "expr_score", "mut_id", "label",
    "pos", "wt", "mut", "is_stop",
    "residue", "aa", "secondary_structure",
    "ss_H", "ss_E", "ss_T", "ss_C"
]

# Select numeric columns except excluded
num_cols = [c for c in df.columns if c not in exclude_cols and df[c].dtype in ["int64", "float64"]]

# Scale
scaler = StandardScaler()
df[num_cols] = scaler.fit_transform(df[num_cols])

# Save scaler
joblib.dump(scaler, "../../models/scaler.pkl")

print("Scaled columns:", len(num_cols))
print("Example scaled features:", num_cols[:10])

Scaled columns: 1290
Example scaled features: ['blosum62', 'grantham', 'delta_charge', 'delta_hydro', 'delta_volume', 'delta_polarity', '0', '1', '2', '3']

In [11]:
df.to_csv("../../data/processed/final_dataset_ready2.csv", index=False)
print("Final dataset saved with shape:", df.shape)

Final dataset saved with shape: (3819, 1314)

In [27]:
# train_model.py
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix
import joblib

# 1. Load dataset
df = pd.read_csv("../../data/processed/final_dataset_ready.csv")

# 2. Features + target
TARGET = "label"   # change if your label column is named differently
X = df.drop(columns=[TARGET])
y = df[TARGET]

# Encode target if categorical
if y.dtype == 'object':
    le = LabelEncoder()
    y = le.fit_transform(y)
    joblib.dump(le, "label_encoder.pkl")

# 3. Identify column types
numeric_features = X.select_dtypes(include=[np.number]).columns.tolist()
categorical_features = X.select_dtypes(exclude=[np.number]).columns.tolist()

print("Numeric features:", numeric_features)
print("Categorical features:", categorical_features)

# 4. Preprocessor
numeric_transformer = StandardScaler()
categorical_transformer = OneHotEncoder(handle_unknown="ignore")

preprocessor = ColumnTransformer(
    transformers=[
        ("num", numeric_transformer, numeric_features),
        ("cat", categorical_transformer, categorical_features),
    ]
)

# 5. Model pipeline
model = RandomForestClassifier(class_weight="balanced", random_state=42)

pipe = Pipeline(steps=[("preprocessor", preprocessor),
                      ("classifier", model)])

# Grid search (optional)
param_grid = {
    "classifier__n_estimators": [100, 200],
    "classifier__max_depth": [None, 10, 20],
}
grid = GridSearchCV(pipe, param_grid, cv=3, n_jobs=-1, scoring="f1_macro")
grid.fit(X, y)

best_model = grid.best_estimator_

# 6. Evaluate
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)
best_model.fit(X_train, y_train)
y_pred = best_model.predict(X_test)

print("Classification Report:\n", classification_report(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

# 7. Save
joblib.dump(best_model, "mutation_model.pkl")
print("Model training complete. Saved mutation_model.pkl")

Numeric features: ['site_RBD', 'site_SARS2', 'bind_lib1', 'bind_lib2', 'ace2_score', 'expr_lib1', 'expr_lib2', 'expr_score', 'pos', 'blosum62', 'grantham', 'delta_charge', 'delta_hydro', 'delta_volume', 'delta_polarity', 'is_stop', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31', '32', '33', '34', '35', '36', '37', '38', '39', '40', '41', '42', '43', '44', '45', '46', '47', '48', '49', '50', '51', '52', '53', '54', '55', '56', '57', '58', '59', '60', '61', '62', '63', '64', '65', '66', '67', '68', '69', '70', '71', '72', '73', '74', '75', '76', '77', '78', '79', '80', '81', '82', '83', '84', '85', '86', '87', '88', '89', '90', '91', '92', '93', '94', '95', '96', '97', '98', '99', '100', '101', '102', '103', '104', '105', '106', '107', '108', '109', '110', '111', '112', '113', '114', '115', '116', '117', '118', '119', '120', '121', '122', '123', '124', '125', '126', '127', '128', '129', '130', '131', '132', '133', '134', '135', '136', '137', '138', '139', '140', '141', '142', '143', '144', '145', '146', '147', '148', '149', '150', '151', '152', '153', '154', '155', '156', '157', '158', '159', '160', '161', '162', '163', '164', '165', '166', '167', '168', '169', '170', '171', '172', '173', '174', '175', '176', '177', '178', '179', '180', '181', '182', '183', '184', '185', '186', '187', '188', '189', '190', '191', '192', '193', '194', '195', '196', '197', '198', '199', '200', '201', '202', '203', '204', '205', '206', '207', '208', '209', '210', '211', '212', '213', '214', '215', '216', '217', '218', '219', '220', '221', '222', '223', '224', '225', '226', '227', '228', '229', '230', '231', '232', '233', '234', '235', '236', '237', '238', '239', '240', '241', '242', '243', '244', '245', '246', '247', '248', '249', '250', '251', '252', '253', '254', '255', '256', '257', '258', '259', '260', '261', '262', '263', '264', '265', '266', '267', '268', '269', '270', '271', '272', '273', '274', '275', '276', '277', '278', '279', '280', '281', '282', '283', '284', '285', '286', '287', '288', '289', '290', '291', '292', '293', '294', '295', '296', '297', '298', '299', '300', '301', '302', '303', '304', '305', '306', '307', '308', '309', '310', '311', '312', '313', '314', '315', '316', '317', '318', '319', '320', '321', '322', '323', '324', '325', '326', '327', '328', '329', '330', '331', '332', '333', '334', '335', '336', '337', '338', '339', '340', '341', '342', '343', '344', '345', '346', '347', '348', '349', '350', '351', '352', '353', '354', '355', '356', '357', '358', '359', '360', '361', '362', '363', '364', '365', '366', '367', '368', '369', '370', '371', '372', '373', '374', '375', '376', '377', '378', '379', '380', '381', '382', '383', '384', '385', '386', '387', '388', '389', '390', '391', '392', '393', '394', '395', '396', '397', '398', '399', '400', '401', '402', '403', '404', '405', '406', '407', '408', '409', '410', '411', '412', '413', '414', '415', '416', '417', '418', '419', '420', '421', '422', '423', '424', '425', '426', '427', '428', '429', '430', '431', '432', '433', '434', '435', '436', '437', '438', '439', '440', '441', '442', '443', '444', '445', '446', '447', '448', '449', '450', '451', '452', '453', '454', '455', '456', '457', '458', '459', '460', '461', '462', '463', '464', '465', '466', '467', '468', '469', '470', '471', '472', '473', '474', '475', '476', '477', '478', '479', '480', '481', '482', '483', '484', '485', '486', '487', '488', '489', '490', '491', '492', '493', '494', '495', '496', '497', '498', '499', '500', '501', '502', '503', '504', '505', '506', '507', '508', '509', '510', '511', '512', '513', '514', '515', '516', '517', '518', '519', '520', '521', '522', '523', '524', '525', '526', '527', '528', '529', '530', '531', '532', '533', '534', '535', '536', '537', '538', '539', '540', '541', '542', '543', '544', '545', '546', '547', '548', '549', '550', '551', '552', '553', '554', '555', '556', '557', '558', '559', '560', '561', '562', '563', '564', '565', '566', '567', '568', '569', '570', '571', '572', '573', '574', '575', '576', '577', '578', '579', '580', '581', '582', '583', '584', '585', '586', '587', '588', '589', '590', '591', '592', '593', '594', '595', '596', '597', '598', '599', '600', '601', '602', '603', '604', '605', '606', '607', '608', '609', '610', '611', '612', '613', '614', '615', '616', '617', '618', '619', '620', '621', '622', '623', '624', '625', '626', '627', '628', '629', '630', '631', '632', '633', '634', '635', '636', '637', '638', '639', '640', '641', '642', '643', '644', '645', '646', '647', '648', '649', '650', '651', '652', '653', '654', '655', '656', '657', '658', '659', '660', '661', '662', '663', '664', '665', '666', '667', '668', '669', '670', '671', '672', '673', '674', '675', '676', '677', '678', '679', '680', '681', '682', '683', '684', '685', '686', '687', '688', '689', '690', '691', '692', '693', '694', '695', '696', '697', '698', '699', '700', '701', '702', '703', '704', '705', '706', '707', '708', '709', '710', '711', '712', '713', '714', '715', '716', '717', '718', '719', '720', '721', '722', '723', '724', '725', '726', '727', '728', '729', '730', '731', '732', '733', '734', '735', '736', '737', '738', '739', '740', '741', '742', '743', '744', '745', '746', '747', '748', '749', '750', '751', '752', '753', '754', '755', '756', '757', '758', '759', '760', '761', '762', '763', '764', '765', '766', '767', '768', '769', '770', '771', '772', '773', '774', '775', '776', '777', '778', '779', '780', '781', '782', '783', '784', '785', '786', '787', '788', '789', '790', '791', '792', '793', '794', '795', '796', '797', '798', '799', '800', '801', '802', '803', '804', '805', '806', '807', '808', '809', '810', '811', '812', '813', '814', '815', '816', '817', '818', '819', '820', '821', '822', '823', '824', '825', '826', '827', '828', '829', '830', '831', '832', '833', '834', '835', '836', '837', '838', '839', '840', '841', '842', '843', '844', '845', '846', '847', '848', '849', '850', '851', '852', '853', '854', '855', '856', '857', '858', '859', '860', '861', '862', '863', '864', '865', '866', '867', '868', '869', '870', '871', '872', '873', '874', '875', '876', '877', '878', '879', '880', '881', '882', '883', '884', '885', '886', '887', '888', '889', '890', '891', '892', '893', '894', '895', '896', '897', '898', '899', '900', '901', '902', '903', '904', '905', '906', '907', '908', '909', '910', '911', '912', '913', '914', '915', '916', '917', '918', '919', '920', '921', '922', '923', '924', '925', '926', '927', '928', '929', '930', '931', '932', '933', '934', '935', '936', '937', '938', '939', '940', '941', '942', '943', '944', '945', '946', '947', '948', '949', '950', '951', '952', '953', '954', '955', '956', '957', '958', '959', '960', '961', '962', '963', '964', '965', '966', '967', '968', '969', '970', '971', '972', '973', '974', '975', '976', '977', '978', '979', '980', '981', '982', '983', '984', '985', '986', '987', '988', '989', '990', '991', '992', '993', '994', '995', '996', '997', '998', '999', '1000', '1001', '1002', '1003', '1004', '1005', '1006', '1007', '1008', '1009', '1010', '1011', '1012', '1013', '1014', '1015', '1016', '1017', '1018', '1019', '1020', '1021', '1022', '1023', '1024', '1025', '1026', '1027', '1028', '1029', '1030', '1031', '1032', '1033', '1034', '1035', '1036', '1037', '1038', '1039', '1040', '1041', '1042', '1043', '1044', '1045', '1046', '1047', '1048', '1049', '1050', '1051', '1052', '1053', '1054', '1055', '1056', '1057', '1058', '1059', '1060', '1061', '1062', '1063', '1064', '1065', '1066', '1067', '1068', '1069', '1070', '1071', '1072', '1073', '1074', '1075', '1076', '1077', '1078', '1079', '1080', '1081', '1082', '1083', '1084', '1085', '1086', '1087', '1088', '1089', '1090', '1091', '1092', '1093', '1094', '1095', '1096', '1097', '1098', '1099', '1100', '1101', '1102', '1103', '1104', '1105', '1106', '1107', '1108', '1109', '1110', '1111', '1112', '1113', '1114', '1115', '1116', '1117', '1118', '1119', '1120', '1121', '1122', '1123', '1124', '1125', '1126', '1127', '1128', '1129', '1130', '1131', '1132', '1133', '1134', '1135', '1136', '1137', '1138', '1139', '1140', '1141', '1142', '1143', '1144', '1145', '1146', '1147', '1148', '1149', '1150', '1151', '1152', '1153', '1154', '1155', '1156', '1157', '1158', '1159', '1160', '1161', '1162', '1163', '1164', '1165', '1166', '1167', '1168', '1169', '1170', '1171', '1172', '1173', '1174', '1175', '1176', '1177', '1178', '1179', '1180', '1181', '1182', '1183', '1184', '1185', '1186', '1187', '1188', '1189', '1190', '1191', '1192', '1193', '1194', '1195', '1196', '1197', '1198', '1199', '1200', '1201', '1202', '1203', '1204', '1205', '1206', '1207', '1208', '1209', '1210', '1211', '1212', '1213', '1214', '1215', '1216', '1217', '1218', '1219', '1220', '1221', '1222', '1223', '1224', '1225', '1226', '1227', '1228', '1229', '1230', '1231', '1232', '1233', '1234', '1235', '1236', '1237', '1238', '1239', '1240', '1241', '1242', '1243', '1244', '1245', '1246', '1247', '1248', '1249', '1250', '1251', '1252', '1253', '1254', '1255', '1256', '1257', '1258', '1259', '1260', '1261', '1262', '1263', '1264', '1265', '1266', '1267', '1268', '1269', '1270', '1271', '1272', '1273', '1274', '1275', '1276', '1277', '1278', '1279', 'rsa', 'dist_to_ACE2', 'dist_to_RBM', 'ss_H', 'ss_E', 'ss_T', 'ss_C', 'rsa_norm']
Categorical features: ['wildtype', 'mutant', 'mutation', 'mutation_RBD', 'mut_id', 'wt', 'mut', 'aa', 'secondary_structure']

MemoryError: Unable to allocate 25.3 MiB for an array with shape (1304, 2546) and data type float64

In [ ]:
# train_torch_model_colab.py
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, StandardScaler, OneHotEncoder
from sklearn.model_selection import train_test_split
import joblib

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
from torch.utils.tensorboard import SummaryWriter
import time

# =====================
# 1. Load Dataset
# =====================
df = pd.read_csv("final_dataset_ready.csv")
TARGET = "label"   # change if needed

X = df.drop(columns=[TARGET])
y = df[TARGET]

# Encode target
if y.dtype == 'object':
    le = LabelEncoder()
    y = le.fit_transform(y)
    joblib.dump(le, "label_encoder.pkl")

# Identify feature types
num_cols = X.select_dtypes(include=[np.number]).columns.tolist()
cat_cols = X.select_dtypes(exclude=[np.number]).columns.tolist()

# Preprocess
scaler = StandardScaler()
ohe = OneHotEncoder(handle_unknown="ignore", sparse_output=False)

X_num = scaler.fit_transform(X[num_cols]) if num_cols else np.empty((len(X),0))
X_cat = ohe.fit_transform(X[cat_cols]) if cat_cols else np.empty((len(X),0))

joblib.dump(scaler, "scaler.pkl")
joblib.dump(ohe, "ohe.pkl")

X_all = np.hstack([X_num, X_cat])
y_all = np.array(y)

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X_all, y_all, test_size=0.2, stratify=y_all, random_state=42
)

# =====================
# 2. Dataset + DataLoader
# =====================
class MutationDataset(Dataset):
    def __init__(self, X, y):
        self.X = torch.tensor(X, dtype=torch.float32)
        self.y = torch.tensor(y, dtype=torch.long)
    def __len__(self):
        return len(self.X)
    def __getitem__(self, idx):
        return self.X[idx], self.y[idx]

train_ds = MutationDataset(X_train, y_train)
test_ds  = MutationDataset(X_test, y_test)

train_loader = DataLoader(train_ds, batch_size=64, shuffle=True)
test_loader  = DataLoader(test_ds, batch_size=64)

# =====================
# 3. Neural Network
# =====================
class MutationNet(nn.Module):
    def __init__(self, input_dim, hidden_dim=256, output_dim=3, dropout=0.3):
        super(MutationNet, self).__init__()
        self.net = nn.Sequential(
            nn.Linear(input_dim, hidden_dim),
            nn.BatchNorm1d(hidden_dim),
            nn.ReLU(),
            nn.Dropout(dropout),
            nn.Linear(hidden_dim, hidden_dim//2),
            nn.BatchNorm1d(hidden_dim//2),
            nn.ReLU(),
            nn.Dropout(dropout),
            nn.Linear(hidden_dim//2, output_dim)
        )
    def forward(self, x):
        return self.net(x)

input_dim = X_all.shape[1]
output_dim = len(np.unique(y_all))
model = MutationNet(input_dim, hidden_dim=512, output_dim=output_dim, dropout=0.4)

# =====================
# 4. Training Setup
# =====================
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)

criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=1e-3)
scheduler = optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode="max", factor=0.5, patience=3)

writer = SummaryWriter(log_dir=f"runs/mutation_{int(time.time())}")

# =====================
# 5. Training Loop with Early Stopping
# =====================
EPOCHS = 50
patience = 7
best_acc = 0
epochs_no_improve = 0

for epoch in range(EPOCHS):
    # Training
    model.train()
    total_loss = 0
    for Xb, yb in train_loader:
        Xb, yb = Xb.to(device), yb.to(device)
        optimizer.zero_grad()
        outputs = model(Xb)
        loss = criterion(outputs, yb)
        loss.backward()
        optimizer.step()
        total_loss += loss.item()

    avg_loss = total_loss / len(train_loader)

    # Validation
    model.eval()
    correct, total = 0, 0
    with torch.no_grad():
        for Xb, yb in test_loader:
            Xb, yb = Xb.to(device), yb.to(device)
            preds = model(Xb).argmax(dim=1)
            correct += (preds == yb).sum().item()
            total += yb.size(0)

    acc = correct / total
    scheduler.step(acc)

    # TensorBoard logging
    writer.add_scalar("Loss/train", avg_loss, epoch)
    writer.add_scalar("Accuracy/val", acc, epoch)

    print(f"Epoch {epoch+1}/{EPOCHS}, Loss={avg_loss:.4f}, Val Acc={acc:.4f}")

    # Early stopping
    if acc > best_acc:
        best_acc = acc
        epochs_no_improve = 0
        torch.save(model.state_dict(), "mutation_model.pt")
    else:
        epochs_no_improve += 1
        if epochs_no_improve >= patience:
            print("⏸ Early stopping triggered!")
            break

print(f"✅ Best Validation Accuracy: {best_acc:.2f}")
writer.close()